### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by stijnvanhoey** [ThierryO/INBOtheme#5]
When installing with `devtools`, following error is thrown:

    Error : .onLoad failed in loadNamespace() for 'INBOtheme', details:
      call: NULL
      error: No geom called GeomBin2d.

I this an incompatibility with my ggplot2 version (I am using version 2.1.0) or am I missing something else?

**Comment by ThierryO** [comment]
This is an old stale fork. The official version is at https://github.com/inbo/INBOtheme
